import type { Metadata } from "next";
import { Inter, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { PlanProvider } from "@/context/PlanContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
});

const oswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FITLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-cBlack text-textP">
        <PlanProvider>
          <Navbar />
          <main>{children}</main>
          <Footer />
        </PlanProvider>

        <ToastContainer
          position="bottom-right"
          autoClose={3000}
          hideProgressBar
          closeButton={false}
          newestOnTop
          toastClassName="!bg-transparent !p-0 !shadow-none"
          className="w-auto! p-0!"
        />
      </body>
    </html>
  );
}
